#!/usr/local/bin/perl -w

use strict;
use warnings 'all';
use ASP4::API;
my $api; BEGIN { $api = ASP4::API->new }

my $url = shift(@ARGV) or die <<"USAGE";
  Usage:  $0 "<url>"
USAGE


my $res = $api->ua->get( $url );
if( $res->is_success )
{
  print $res->as_string;
}
else
{
  warn "ERROR - Response As Follows:\n" . ("="x80) . "\n\n" . $res->as_string;
}# end if()

